
CREATE TABLE PERSON
(
  PersonID INT NOT NULL Identity(1,1),
  Email VARCHAR(100) NOT NULL UNIQUE,
  Password VARCHAR(50) NOT NULL, 
  Created_at DATETIME NULL DEFAULT GETDATE(),
  First_Name NVARCHAR(50) NULL, 
  Last_Name NVARCHAR(50) NULL,
  PRIMARY KEY (PersonID)
);

CREATE TABLE PERSON_PERMISSIONS
(
  Permission INT NOT NULL,
  PersonID INT NOT NULL,
  PRIMARY KEY (Permission, PersonID),
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE ADDRESSES
(
  ID INT NOT NULL Identity(1,1),
  City NVARCHAR(50) NULL,
  Street NVARCHAR(100) NULL,
  BuildingNumber VARCHAR(20) NULL,
  ApartmentNumber VARCHAR(20) NULL,
  ZipCode VARCHAR(20) NULL,
  PersonID INT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE SET NULL
);

CREATE TABLE ADDRESSES_AND_CONTACT_PHONENUMBER
(
  PhoneNumber VARCHAR(20) NOT NULL,
  AddressID INT NOT NULL,
  PRIMARY KEY (PhoneNumber, AddressID),
  FOREIGN KEY (AddressID) REFERENCES ADDRESSES(ID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST
(
  WichListID INT NOT NULL Identity(1,1),
  NumberOfProducts INT NULL Default 0,
  PRIMARY KEY (WichListID)
);

CREATE TABLE ENDUSER
(
  EndUserID INT NOT NULL ,
  WichListID INT NULL,
  PersonID INT NOT NULL Unique, 
  PRIMARY KEY (EndUserID),
  FOREIGN KEY (WichListID) REFERENCES WISHLIST(WichListID) ON DELETE SET NULL,
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE SELLER
(
  SellerID INT NOT NULL ,
  StoreName NVARCHAR(100) NULL,
  Store_Description NVARCHAR(max) NULL,
  StoreLogo VARBINARY(max) NULL,  
  SellerWallet_Balance DECIMAL(12,2) NULL DEFAULT 0.00,
  PersonID INT NOT NULL Unique, 
  PRIMARY KEY (SellerID),
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE FOLLOW
(
  Followed_at DATE NULL DEFAULT GetDate(),
  EndUserID INT NOT NULL,
  SellerID INT NOT NULL,
  PRIMARY KEY (EndUserID, SellerID),
  FOREIGN KEY (EndUserID) REFERENCES ENDUSER(EndUserID),
  FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID) ON DELETE CASCADE
);

CREATE TABLE SHIPMENT
(
  ShipmentID INT NOT NULL IDENTITY(1,1),
  Carrier NVARCHAR(100) NULL,
  Shipment_Status TINYINT NULL,
  Shipped_at_time DATETIME NULL,
  Delivered_at_time DATE NULL,
  Tracking_Number VARCHAR(50) NULL,
  PRIMARY KEY (ShipmentID)
);

CREATE TABLE CATEGORY
(
  CategoryID TINYINT NOT NULL Identity(1,1),
  Category_Name NVARCHAR(25) NOT NULL,
  PRIMARY KEY (CategoryID)
);

CREATE TABLE PAYOUT
(
  PayoutID INT NOT NULL IDENTITY(1,1),
  Amount DECIMAL(12,2) NULL,
  Status INT NULL,
  Request_at_time DATETIME NULL,
  Paid_at DATETIME NULL Default GetDate(),
  SellerID INT NULL,
  PRIMARY KEY (PayoutID),
  FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID) ON DELETE SET NULL
);

CREATE TABLE [Orders]
(
  OrderID INT NOT NULL IDENTITY(1,1),
  Status TINYINT NULL,
  ShippingCost DECIMAL(10,2) NULL,
  TotalAmount DECIMAL(12,2) NULL,
  PaymentID INT NOT NULL,
  PaymentMethod TINYINT NULL,	-- <----------- Important
  PSP VARCHAR(50) NULL,	-- <----------- Important
  PaymentStatus TINYINT NULL,
  Transaction_REF Varchar(50) NULL,
  Paid_at DATETIME NOT NULL,
  ShipmentID INT NULL,
  SellerID INT NULL,
  EndUserID INT NULL,
  PRIMARY KEY (OrderID),
  FOREIGN KEY (ShipmentID) REFERENCES SHIPMENT(ShipmentID) ON DELETE SET NULL,
  FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID) ON DELETE NO ACTION,
  FOREIGN KEY (EndUserID) REFERENCES ENDUSER(EndUserID) ON DELETE NO ACTION
);

CREATE TABLE STANDARD_ORDER
(
  --StandardOrderID INT NOT NULL Identity(1,1),
  OrderID INT NOT NULL Unique,
  --PRIMARY KEY (StandardOrderID),
  PRIMARY KEY (OrderID),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE CUSTOMIZED_ORDER
(
  --Customized_OrderID INT NOT NULL Identity(1,1), 
  OrderID INT NOT NULL Unique,
  --PRIMARY KEY (Customized_OrderID),
  PRIMARY KEY (OrderID ),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE [PRODUCTS]
(
  ProductID INT NOT NULL Identity(1,1),
  ProductName NVARCHAR(50) NOT NULL, 
  Cover VARBINARY(max) NULL,        
  CategoryID TINYINT NULL,
  SellerID INT NULL,
  PRIMARY KEY (ProductID),
  FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE SET NULL,
  FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID) ON DELETE CASCADE
);

CREATE TABLE PRODUCT_IMAGES
(
  Product_ImageID INT NOT NULL Identity(1,1),
  ProductImage VARBINARY(max) NOT NULL,
  Upload_date DATE NOT NULL DEFAULT GetDate(),
  ProductID INT NOT NULL,
  PRIMARY KEY (Product_ImageID, ProductID),
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID) ON DELETE CASCADE
);

CREATE TABLE REVIEWING_AND_RATING
(
  Rating FLOAT NOT NULL,
  Comment NVARCHAR(500) NULL,
  Created_at DATETIME NOT NULL DEFAULT GETDATE(),
  EndUserID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (EndUserID, ProductID),
  FOREIGN KEY (EndUserID) REFERENCES ENDUSER(EndUserID),
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID) ON DELETE CASCADE
);

CREATE TABLE CONSIST_OF
(
  Quantity INT NOT NULL,
  Price_at_purchase DECIMAL(12,2) NOT NULL,
  OrderID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (OrderID, ProductID),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID)
);

CREATE TABLE Whishlist_Contain
(
  WichListID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (WichListID, ProductID),
  FOREIGN KEY (WichListID) REFERENCES WISHLIST(WichListID) ON DELETE CASCADE,
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID) ON DELETE CASCADE
);

CREATE TABLE CART
(
  CartID INT NOT NULL IDENTITY(1,1),
  CreatorID INT NULL,
  Created_at DATETIME NOT NULL DEFAULT GetDate(),
  PRIMARY KEY (CartID),
  FOREIGN KEY (CreatorID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE Cart_Contain
(
  Number_of_Products INT NULL DEFAULT 0,
  CartID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (CartID, ProductID),
  FOREIGN KEY (CartID) REFERENCES CART(CartID) ON DELETE CASCADE,
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID) ON DELETE NO ACTION
);

CREATE TABLE SYSTEMADMIN
(
  AdminID INT NOT NULL IDENTITY(1,1),
  SupervisorID INT NULL, 
  PersonID INT NOT NULL Unique,
  PRIMARY KEY (AdminID),
  FOREIGN KEY (SupervisorID) REFERENCES SYSTEMADMIN(AdminID),
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE [CONVERSATION]
(
  ConversationID INT NOT NULL Identity(1,1),
  Created_at DATETIME NOT NULL Default GetDate(),
  LastMessageAt DATETIME NULL,
  EndUserID INT NOT NULL,
  SellerID INT NOT NULL,
  PRIMARY KEY (ConversationID),
  FOREIGN KEY (EndUserID) REFERENCES ENDUSER(EndUserID),
  FOREIGN KEY (SellerID) REFERENCES SELLER(SellerID)
);

CREATE TABLE MESSAGES
(
  MessageID INT NOT NULL Identity(1,1) ,
  MessageContent NVARCHAR(max) NOT NULL ,
  Sent_At DATETIME2(5) NOT NULL Default GetDate() ,
  IsRead BIT NULL Default 0 ,
  ConversationID INT NOT NULL ,
  PRIMARY KEY (MessageID, ConversationID) ,
  FOREIGN KEY (ConversationID) REFERENCES [CONVERSATION](ConversationID) ON DELETE CASCADE
);

CREATE TABLE [NOTIFICATION]
(
  Notification_ID INT NOT NULL IDENTITY(1,1),
  Tittle NVARCHAR(100) NOT NULL,
  NotificationContent NVARCHAR(700) NOT NULL,
  Created_at DATETIME NOT NULL DEFAULT GetDate(),
  Is_Read BIT NULL DEFAULT 0,
  PersonID INT NOT NULL,
  PRIMARY KEY (Notification_ID),
  FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID) ON DELETE CASCADE
);

CREATE TABLE RETURNS
(
  ReturnID INT NOT NULL Identity(1,1),
  Reason NVARCHAR(1000) NOT NULL,
  Status TINYINT NULL,
  RequestDate DATETIME NOT NULL DEFAULT GetDate(),
  OrderID INT NOT NULL,
  PRIMARY KEY (ReturnID),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

CREATE TABLE PROOF_AS_IMAGES
(
  ImageID INT NOT NULL IDENTITY(1,1),
  Evidence_URL VARCHAR(500) NULL,
  The_Image VarBinary(max) NULL,
  ReturnID INT NOT NULL,
  PRIMARY KEY (ImageID, ReturnID),
  FOREIGN KEY (ReturnID) REFERENCES RETURNS(ReturnID) ON DELETE CASCADE
);

CREATE TABLE CUSTOM_REQUEST
(
  RequestID INT NOT NULL IDENTITY(1,1),
  ItemName NVARCHAR(100) NOT NULL,
  Description NVARCHAR(1000) NOT NULL,
  Visibility BIT NOT NULL DEFAULT 1,
  Quantity TINYINT NULL DEFAULT 1,
  Lenght FLOAT NULL,
  Width FLOAT NULL,
  Hight FLOAT NULL,
  Matrial NVARCHAR(255) NULL,
  Desired_Delivery_Date DATE NULL,
  Created_at DATE NOT NULL DEFAULT GetDate(),
  Status TINYINT NULL,
  EndUserID INT NOT NULL,
  CategoryID TINYINT NOT NULL,
  PRIMARY KEY (RequestID),
  FOREIGN KEY (EndUserID) REFERENCES ENDUSER(EndUserID),
  FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID)
);

CREATE TABLE VISUAL_INSPIRATION
(
  ImageID INT NOT NULL IDENTITY(1,1),
  The_Image VARBINARY(max) NULL,
  ImageURL VARCHAR(500) NULL,
  RequestID INT NOT NULL,
  PRIMARY KEY (ImageID, RequestID),
  FOREIGN KEY (RequestID) REFERENCES CUSTOM_REQUEST(RequestID) ON DELETE CASCADE
);

CREATE TABLE VOICEMEMO
(
  RecordingID INT NOT NULL IDENTITY(1,1),
  Duration FLOAT NULL,
  Send_at DATETIME NULL DEFAULT GETDATE(),
  Record VARBINARY(MAX) NULL, -- Updated to handle arbitrary binary voice objects safely
  RequestID INT NOT NULL,
  PRIMARY KEY (RecordingID, RequestID),
  FOREIGN KEY (RequestID) REFERENCES CUSTOM_REQUEST(RequestID) ON DELETE CASCADE
);

CREATE TABLE COLOR_PALETTE
(
  Color_PaletteID INT NOT NULL IDENTITY(1,1),
  Color_Code VARCHAR(20) NOT NULL,
  Color_Description NVARCHAR(100) NOT NULL,
  RequestID INT NOT NULL,
  PRIMARY KEY (Color_PaletteID, RequestID),
  FOREIGN KEY (RequestID) REFERENCES CUSTOM_REQUEST(RequestID) ON DELETE CASCADE
);

CREATE TABLE COUPONS
(
  CouponID INT NOT NULL IDENTITY(1,1),
  Description NVARCHAR(500) NOT NULL,
  Created_at DATETIME NOT NULL DEFAULT GetDate(),
  Status BIT NULL DEFAULT 1,
  CouponCode VarChar(50) Unique,
  Expired_Date DATETIME NULL,
  Scope TINYINT NOT NULL,
  CreatorID INT NOT NULL,
  StoreID INT NULL,
  PRIMARY KEY (CouponID),
  CONSTRAINT Check_Coupon_Scope CHECK(Scope IN (0,10,11,21,20)),
  FOREIGN KEY (CreatorID) REFERENCES PERSON(PersonID) ON DELETE NO ACTION,
  FOREIGN KEY (StoreID) REFERENCES Seller(SellerID) ON DELETE NO ACTION

);

CREATE TABLE Coupon_Product
(
  Coupon_ProductID INT IDENTITY(1,1),
  CouponID INT NOT NULL,
  ProductID INT NOT NULL,
  PRIMARY KEY (Coupon_ProductID),
  FOREIGN KEY (CouponID) REFERENCES COUPONS(CouponID) ON DELETE CASCADE,
  FOREIGN KEY (ProductID) REFERENCES [PRODUCTS](ProductID) ON DELETE CASCADE
);

CREATE TABLE USER_COUPONS
(
  Used_CouponID INT NOT NULL IDENTITY(1,1),
  Used_at DATETIME NOT NULL DEFAULT GETDATE(), 
  CouponID INT NOT NULL,
  UserID INT NOT NULL,
  OrderID INT NOT NULL,
  PRIMARY KEY (Used_CouponID),
  FOREIGN KEY (CouponID) REFERENCES COUPONS(CouponID),
  FOREIGN KEY (UserID) REFERENCES PERSON(PersonID),
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);



